# syntax=docker/dockerfile:1
FROM python:3.11-slim-bookworm

# Prevent Python from writing .pyc files to disk and force stdout/stderr to flush
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install 'uv' (fast Python package installer/resolver)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy project configuration
COPY pyproject.toml README.md ./
COPY src/ src/

# Sync and install the project in the container's system environment using uv
RUN uv pip install --system -e .

# Create an unprivileged user to run the server for security
RUN useradd -m mcpuser
USER mcpuser

# The entrypoint is the script generated by [project.scripts] in pyproject.toml
ENTRYPOINT ["mcp-denue"]
